name: Github Action Hello world
on: push 
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Olá mundo!"
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: List files
        run: ls ${{ github.workspace }}
